### PR TITLE
Drop php 5 5 support

### LINKED ISSUE #10: Drop Support for PHP 5.5

### PR DESCRIPTION
**Pull request by elstamey**
this resolves #10

### CODE REVIEW

**Comment by rocketpastsix** [comment]
looks like there is an error in the composer file.

**Comment by elstamey** [comment]
I didn't see that last night, but I see it now.  It's odd that travis is putting the X on the `.travis.yml` file

**Comment by elazar** [comment]
@elstamey @rocketpastsix I've tried re-running the build, but unfortunately, it doesn't appear that this is a transient issue. One difference I noticed here versus [a PR without this issue](https://github.com/phergie/phergie-irc-parser/pull/44) is that this repository isn't using `phergie/phergie-irc-bot-react-development`. Can we try transitioning from explicitly specifying dev dependencies to using that instead, to see if it resolves the problem?

**Comment by rocketpastsix** [comment]
Ill +1 what @elazar says about using the ```phergie/phergie-irc-bot-react-development``` library.

**Comment by elstamey** [comment]
For clarification, this is meant to be in `require-dev`?

**Comment by rocketpastsix** [comment]
yes, it should be.

**Comment by elstamey** [comment]
My adding that one package to require-dev is causing more conflicts for me, so I'll have to look at this tonight when I can focus a bit more.

**Comment by elazar** [comment]
@elstamey No worries, get to it as you're able. For clarity, that one package should be able to replace all the packages currently listed in `require-dev`.

**Comment by rocketpastsix** [comment]
looks good!

**Comment by elstamey** [comment]
wow, you're fast!  AND while drinking a beverage!

**Comment by rocketpastsix** [comment]
who says Im drinking? :)

**Comment by elstamey** [comment]
your photo.

**Pull request merged**
